// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0lhZES5rU5rJuYgHl_pNjhjAxcPv4dX4',
    appId: '1:739710601701:web:fb45477d4ffc7f6e74c70c',
    messagingSenderId: '739710601701',
    projectId: 'portfolio-4d43d',
    authDomain: 'portfolio-4d43d.firebaseapp.com',
    storageBucket: 'portfolio-4d43d.appspot.com',
    measurementId: 'G-6PLG5B6D31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX9F40Zd3VrZMIRLB4kcvef7DHYJ6fVYA',
    appId: '1:739710601701:android:0717347a8b12967374c70c',
    messagingSenderId: '739710601701',
    projectId: 'portfolio-4d43d',
    storageBucket: 'portfolio-4d43d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNFd1rxVb6JxOT_j0X2mP5EpDl8V4gug',
    appId: '1:739710601701:ios:6bc4dc7b979460d474c70c',
    messagingSenderId: '739710601701',
    projectId: 'portfolio-4d43d',
    storageBucket: 'portfolio-4d43d.appspot.com',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNFd1rxVb6JxOT_j0X2mP5EpDl8V4gug',
    appId: '1:739710601701:ios:6bc4dc7b979460d474c70c',
    messagingSenderId: '739710601701',
    projectId: 'portfolio-4d43d',
    storageBucket: 'portfolio-4d43d.appspot.com',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0lhZES5rU5rJuYgHl_pNjhjAxcPv4dX4',
    appId: '1:739710601701:web:7753353df535c4f874c70c',
    messagingSenderId: '739710601701',
    projectId: 'portfolio-4d43d',
    authDomain: 'portfolio-4d43d.firebaseapp.com',
    storageBucket: 'portfolio-4d43d.appspot.com',
    measurementId: 'G-DWMWV5E6B9',
  );
}
